### ISSUE TITLE
Custom data at test time

### ISSUE THREAD

**Issue by eljdos** [google-research/lag#2]
Hello,

Thank you so very much for the impressive work and for making it open source.

Out of curiosity I was wondering if you are going to explain how one could get it to work with custom datasets (by that i mean not from the list of supported datasets).

Thank you so very much and best regards,

**Comment by david-berthelot** [comment]
One way is to look at `scripts/create_datasets.py`, we convert datasets into a TFRecord file of tf.Example with two fields:
- `image` is a string containing the png encoded image.
- `label` is an int64 (unused, you can set it to 0)

Once you created two record files for your dataset (train and test), you can simply modify `libml/data.py` to add your dataset to the dictionary. And then when calling `lag.py` you would need to add `--dataset=your_dataset_name`.

**Comment by eljdos** [comment]
Thank you very much for the answer :)
