### ISSUE TITLE
critic output

### ISSUE THREAD

**Issue by Medabid1** [google-research/lag#6]
https://github.com/google-research/lag/blob/03333f55cfc2826e3eb4865f78e306b35ba6d8d1/lag.py#L98

Hello, could you please, explain why multiply y  with center at the output of the critic ?

**Comment by david-berthelot** [comment]
To make the expected sum 0 centered and the slope symmetric around 0. As you can see, each convolution is followed by a leaky_relu which reduces the slope of negative numbers. Multiplying the channels with [-1, 1, -1, 1, ...] makes their sum 0 centered and gradient slope uniform between positive and negative values. The goal is not to favor the critic convergence on either real or fake samples.

**Comment by Medabid1** [comment]
Thanks a lot for the explanation,  Is there a paper that you can refer me to it, so i can read more about it ? or is it just an trick/techniques for training ? 

Thank your for your time.

**Comment by david-berthelot** [comment]
I remember first seeing this idea in a paper a long time ago, unfortunately I couldn't remember where. Sorry about that.

**Comment by Medabid1** [comment]
No problem, Thanks.
